name: Super-Linter
on: push

jobs:
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: src/deps/.*|src/game/assets/fonts/helvetiker_regular.typeface.js|src/game/assets/fonts/helvetiker_bold.typeface.js|src/common/VREffect.js|src/common/VRControls.js|src/common/PointerLockControls.js
          OUTPUT_DETAILS: detailed
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_JSON: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
